
import type { Metadata } from "next";
import Sidebar from "../components/shared/Sidebar";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen my-2 w-[90%] m-auto">
      <div className="flex justify-between">
        <div className="w-[20%]">
          <Sidebar />
        </div>
        <div className="w-[80%]  rounded-box ml-2">{children}</div>
      </div>
    </div>
  );
}
